# Generated by Django 2.2.7 on 2019-11-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_desc',
            field=models.TextField(max_length=500, verbose_name='Product Description'),
        ),
    ]
