# Generated by Django 2.2.7 on 2019-11-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20191130_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodcut_category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=0, upload_to='products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_subcategory',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
