# Generated by Django 2.2.7 on 2019-11-30 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_auto_20191130_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodcut_category',
            new_name='product_category',
        ),
    ]
