# Generated by Django 2.2.7 on 2019-12-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
